### ISSUE TITLE
[FEATURE Request] padEnd (padRight)

### ISSUE THREAD

**Issue by topaxi** [topaxi/ember-pad#1]
Currently only padStart (as pad) is supported.

**Comment by buschtoens** [comment]
I'll submit a PR in the evening (CEST).

Which helper names would you prefer?
1. only `padStart`, `padEnd`
2. only `padLeft`, `padRight`
3. `padStart`, `padEnd` and `pad` as an alias for `padStart`
4. `padLeft`, `padRight` and `pad` as an alias for `padLeft`
5. All five

The template literal function would get the same naming scheme.

**Comment by topaxi** [comment]
I'd prefer `padStart` and `padEnd` to align with https://github.com/tc39/proposal-string-pad-start-end and `pad` as an alias for `padStart` to keep backwards compatibility and easier use for the (I guess) more common case.

Thanks! :+1:

**Comment by topaxi** [comment]
Implemented in #2
